/**
 * The MIT License (MIT)
 *
 * MSUSEL Sonar Quamoco Plugin
 * Copyright (c) 2015-2017 Montana State University, Gianforte School of Computing,
 * Software Engineering Laboratory
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package edu.montana.gsoc.msusel.sonar.quamoco.profiles;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.Charset;
import java.nio.file.Path;
import java.nio.file.Paths;

import com.google.common.io.Files;

import edu.montana.gsoc.msusel.sonar.quamoco.profiles.xml.QuamocoProfile;

/**
 * Class used to export Quamoco Quality profiles to an XML document.
 *
 * @author Isaac Griffith
 * @version 1.1.1
 */
public class QuamocoProfileExporter {

    /**
     * Export the provide file to an XML document at the provided location.
     * 
     * @param profile
     *            The profile to be exported.
     * @param loc
     *            Full path name of the file to be written.
     */
    public void exportProfile(final QuamocoProfile profile, final String loc)
    {
        final Path p = Paths.get(loc);
        try (PrintWriter writer = new PrintWriter(Files.newWriter(p.toFile(), Charset.forName("UTF-8"))))
        {

            writer.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- Generated by SonarQube -->\n"
                    .concat(profile.toXml()));

        }
        catch (final IOException e)
        {
            System.err.println("Fail to export the Quamoco profile.");
        }
    }
}
